# frozen_string_literal: true

puts "Seeding Dentivara functional data..."

users_data = [
  { name: "Clinic Owner", email: "owner@dentivara.local", role: :clinic_owner },
  { name: "Dr. Maria Reyes", email: "dentist1@dentivara.local", role: :dentist },
  { name: "Dr. Julian Santos", email: "dentist2@dentivara.local", role: :dentist },
  { name: "Ana Cruz", email: "reception@dentivara.local", role: :receptionist },
  { name: "Paolo Santos", email: "billing@dentivara.local", role: :billing_staff },
  { name: "System Admin", email: "sysadmin@dentivara.local", role: :system_admin },
  { name: "Patient Portal User", email: "patientportal@dentivara.local", role: :patient }
]

users = users_data.map do |attrs|
  user = User.find_or_initialize_by(email: attrs[:email])
  user.assign_attributes(attrs)
  user.password = "dentivara123"
  user.password_confirmation = "dentivara123"
  user.save!
  user
end

dentists = users.select(&:dentist?)

services_data = [
  ["Routine Checkup", "General oral check and consultation", 1200, 30],
  ["Teeth Cleaning", "Full prophylaxis cleaning service", 2500, 45],
  ["Root Canal", "Root canal therapy procedure", 12000, 90],
  ["Braces Adjustment", "Orthodontic maintenance adjustment", 1800, 30],
  ["Teeth Whitening", "In-clinic whitening treatment", 8500, 60]
]

services_data.each do |name, description, price, minutes|
  service = ClinicService.find_or_initialize_by(name: name)
  service.description = description
  service.base_price = price
  service.duration_minutes = minutes
  service.active = true
  service.save!
end

prescription_template = DocumentTemplate.find_or_initialize_by(name: "Standard Prescription")
prescription_template.assign_attributes(
  kind: "prescription",
  active: true,
  header_text: "Dentivara Dental Clinic\nOfficial Prescription",
  body_template: "Patient: {{patient_name}}\nDate: {{today}}\n\nRx:\n- Medication: ____________________\n- Dosage: ______________________\n- Instructions: _________________\n\nDentist: {{dentist_name}}",
  footer_text: "This document is generated by Dentivara.",
  digital_signature_name: "Dr. Maria Reyes",
  digital_signature_title: "Licensed Dentist"
)
prescription_template.save!

certificate_template = DocumentTemplate.find_or_initialize_by(name: "Dental Certificate")
certificate_template.assign_attributes(
  kind: "dental_certificate",
  active: true,
  header_text: "Dentivara Dental Clinic\nDental Certificate",
  body_template: "This certifies that {{patient_name}} was seen on {{today}} for dental evaluation and treatment.",
  footer_text: "For clinic verification only.",
  digital_signature_name: "Dr. Julian Santos",
  digital_signature_title: "Dental Practitioner"
)
certificate_template.save!

25.times do |i|
  first = ["Liam", "Olivia", "Noah", "Emma", "Sophia", "James", "Lucas", "Mia", "Ava", "Ethan"].sample
  last = ["Garcia", "Reyes", "Santos", "Cruz", "Mendoza", "Torres", "Flores", "Ramos"].sample

  patient = Patient.find_or_initialize_by(email: "patient#{i + 1}@example.com")
  patient.first_name = first
  patient.last_name = last
  patient.birth_date = Date.new(1985 + rand(20), rand(1..12), rand(1..28))
  patient.phone = "09#{rand(10**9).to_s.rjust(9, '0')}"
  patient.emergency_contact_name = "#{first} Contact"
  patient.emergency_contact_phone = "09#{rand(10**9).to_s.rjust(9, '0')}"
  patient.medical_history = "No severe allergies. Prior dental fillings."
  patient.consented_at = Time.current - rand(1..200).days
  patient.save!

  if i.zero?
    portal_user = User.find_by(email: "patientportal@dentivara.local")
    patient.update!(user: portal_user)
  end

  next if i < 5

  2.times do |j|
    start_time = nil
    duration = [30, 45, 60, 90].sample.minutes
    assigned_dentist = nil
    20.times do
      candidate_start = Time.current.beginning_of_day + rand(1..20).days + (9 + rand(8)).hours
      candidate_end = candidate_start + duration
      candidate_dentist = dentists.sample
      overlap = Appointment.where(user_id: candidate_dentist.id)
                           .where("starts_at < ? AND ends_at > ?", candidate_end, candidate_start)
                           .exists?
      next if overlap

      start_time = candidate_start
      assigned_dentist = candidate_dentist
      break
    end
    next if start_time.blank?

    appt = Appointment.create!(
      patient: patient,
      user: assigned_dentist,
      source: Appointment::BOOKING_SOURCES.sample,
      booking_type: Appointment::BOOKING_TYPES.sample,
      starts_at: start_time,
      ends_at: start_time + duration,
      status: j.zero? ? "confirmed" : Appointment::STATUSES.sample,
      operatory: ["Room A", "Room B", "Chair 1", "Chair 2"].sample,
      notes: "Follow-up for service review"
    )

    record = TreatmentRecord.create!(
      patient: patient,
      user: appt.user,
      appointment: appt,
      service_type: ClinicService.order(:id).sample.name,
      clinical_notes: "Procedure completed with stable findings.",
      cost: rand(1200..15000),
      performed_on: appt.starts_at.to_date
    )

    total = record.cost.to_d
    paid = [0, total / 2, total].sample
    invoice = Invoice.create!(
      patient: patient,
      treatment_record: record,
      status: paid == total ? "paid" : (paid.positive? ? "partially_paid" : "approved"),
      total_amount: total,
      balance_amount: total - paid,
      issued_on: appt.starts_at.to_date,
      approved_by_dentist_at: appt.starts_at,
      approved_by_admin_at: appt.starts_at + 2.hours
    )

    next unless paid.positive?

    Payment.create!(
      invoice: invoice,
      amount: paid,
      paid_on: appt.starts_at.to_date,
      method: %w[cash card transfer].sample,
      reference_code: "PAY-#{SecureRandom.hex(4).upcase}"
    )
  end
end

Patient.includes(:user).where.not(user_id: nil).find_each do |patient|
  IntakeFormSubmission.find_or_create_by!(
    patient: patient,
    submitted_by_user: patient.user,
    source: "online",
    status: "submitted"
  ) do |submission|
    submission.payload = {
      "chief_concern" => "Mild tooth sensitivity on upper left molars",
      "allergies" => "None reported",
      "current_medication" => "Vitamin C only",
      "preferred_contact" => patient.email
    }
  end
end

Patient.limit(10).each do |patient|
  user = User.where(role: [:clinic_owner, :system_admin, :dentist]).order(:id).first
  next if user.blank?

  PatientConsent.find_or_create_by!(
    patient: patient,
    user: user,
    consent_type: "data_privacy",
    document_version: "DPA-v1.0",
    consented_at: [patient.consented_at, Time.current].compact.first
  ) do |consent|
    consent.metadata = { source: "seed", jurisdiction: "PH Data Privacy Act" }
  end
end

puts "Seed complete. Login accounts use password: dentivara123"
